### ISSUE TITLE
Get Rotation causing test to fail

### ISSUE THREAD

**Issue by OroArmor** [robototes/InfiniteRecharge2020#22]
https://github.com/robototes/InfiniteRecharge2020/blob/7528bfe46df7ee6224d7a8ebb619c46d384d207a/src/test/java/frc/team2412/robot/subsystems/DriveBaseSubsystemTest.java#L71

The gyro variable is created, but not initialized.

**Comment by SumedhP** [comment]
It's because it is using your vector class and not the gyro to get the angle. Would you like me too switch that?
