### ISSUE TITLE
Wrong solenoid types for most everything

### ISSUE THREAD

**Issue by jamesdooley4** [robototes/InfiniteRecharge2020#49]
@SumedhP or someone else, only lift is using a double solenoid - everything else is using a single solenoid with a spring return.  Please fix the code to match, and update the solenoid port #s so they don't overlap or fall outside the range 0..7 that are physically possible.

**Comment by jamesdooley4** [comment]
See https://github.com/jamesdooley4/InfiniteRecharge2020/pull/9/files for one way to fix this, as well as several other crashing issues in the robot code.  @OroArmor - you or someone else should port those changes to the main branch so the main robot code would be functional...

**Comment by SumedhP** [comment]
This
